name: data-analysis-env

channels:
  - conda-forge

dependencies:
  - python=3.13
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyter
  - ipykernel
  - plotly
  - notebook
